import PDFDocument from "pdfkit";

/* ============================================================
   BRAND COLORS & TYPOGRAPHY CONSTANTS
   ============================================================ */
const COLORS = {
    primary: "#4f46e5",  // Indigo-600
    secondary: "#0ea5e9",  // Sky-500
    accent: "#f59e0b",  // Amber-500
    success: "#10b981",  // Emerald-500
    danger: "#f43f5e",  // Rose-500
    dark: "#1e1b4b",  // Dark navy
    darkGray: "#374151",
    midGray: "#6b7280",
    lightGray: "#e5e7eb",
    white: "#ffffff",
    bodyText: "#111827",
};

const FONTS = {
    title: 24,
    h1: 18,
    h2: 14,
    h3: 12,
    body: 10,
    small: 8.5,
    caption: 8,
};

const MARGIN = { top: 50, left: 50, right: 50, bottom: 60 };

/* ============================================================
   HELPER UTILITIES
   ============================================================ */

/** Format a rupee value */
function inr(amount) {
    if (!amount && amount !== 0) return "N/A";
    return `\u20b9${Number(amount).toLocaleString("en-IN")}`;
}

/** Clamp text to maxLen characters */
function clamp(text, maxLen = 200) {
    if (!text) return "";
    return text.length > maxLen ? text.substring(0, maxLen - 3) + "..." : text;
}

/** Period label and emoji */
function periodLabel(period) {
    return { morning: "🌅 Morning", afternoon: "☀️ Afternoon", evening: "🌙 Evening" }[period] || period;
}

/**
 * Draw a horizontal rule at current Y
 */
function drawHR(doc, color = COLORS.lightGray, width = 1) {
    const y = doc.y;
    doc
        .moveTo(MARGIN.left, y)
        .lineTo(doc.page.width - MARGIN.right, y)
        .strokeColor(color)
        .lineWidth(width)
        .stroke();
    doc.moveDown(0.4);
}

/**
 * Draw a filled rectangle strip (section header bar)
 */
function drawSectionBar(doc, label, color = COLORS.primary) {
    const pageW = doc.page.width;
    const barH = 26;
    const y = doc.y;

    doc
        .rect(MARGIN.left, y, pageW - MARGIN.left - MARGIN.right, barH)
        .fill(color);

    doc
        .fillColor(COLORS.white)
        .fontSize(FONTS.h2)
        .font("Helvetica-Bold")
        .text(label, MARGIN.left + 10, y + 7, {
            width: pageW - MARGIN.left - MARGIN.right - 20,
        });

    doc.moveDown(1.6);
}

/**
 * Draw a text-based progress bar (for budget allocation)
 * Shows filled blocks proportional to pct
 */
function drawTextBar(doc, label, value, total, barColor, x, y, barWidth = 180) {
    const pct = total > 0 ? Math.min(1, value / total) : 0;
    const filled = Math.round(pct * 20); // 20-block bar
    const empty = 20 - filled;
    const bar = "█".repeat(filled) + "░".repeat(empty);
    const pctStr = `${Math.round(pct * 100)}%`;

    doc
        .fillColor(COLORS.darkGray)
        .fontSize(FONTS.body)
        .font("Helvetica-Bold")
        .text(`${label}`, x, y)
        .fillColor(barColor)
        .font("Helvetica")
        .text(bar, x, y + 12, { width: barWidth })
        .fillColor(COLORS.midGray)
        .text(`${pctStr}  ${inr(value)}`, x + barWidth + 8, y + 12);
}

/**
 * Add a footer to the current page: page number + branding
 */
function addFooter(doc, pageNum) {
    const pageW = doc.page.width;
    const footY = doc.page.height - 35;

    doc
        .moveTo(MARGIN.left, footY - 6)
        .lineTo(pageW - MARGIN.right, footY - 6)
        .strokeColor(COLORS.lightGray)
        .lineWidth(0.5)
        .stroke();

    doc
        .fillColor(COLORS.midGray)
        .fontSize(FONTS.caption)
        .font("Helvetica")
        .text(
            "Generated by Around the World — AI-Driven Intelligent Travel Companion",
            MARGIN.left,
            footY,
            { width: pageW - MARGIN.left - MARGIN.right - 60, align: "left" }
        )
        .text(`Page ${pageNum}`, pageW - MARGIN.right - 40, footY, {
            width: 50,
            align: "right",
        });
}

/* ============================================================
   SECTION 1 — COVER PAGE
   ============================================================ */
function drawCoverPage(doc, trip) {
    const pageW = doc.page.width;
    const pageH = doc.page.height;

    // Deep navy background strip at top (full width)
    doc.rect(0, 0, pageW, 200).fill(COLORS.dark);

    // Accent corner stripe
    doc.rect(0, 0, 8, 200).fill(COLORS.primary);

    // App title
    doc
        .fillColor(COLORS.white)
        .fontSize(11)
        .font("Helvetica")
        .text("AROUND THE WORLD", MARGIN.left, 38, { characterSpacing: 3 });

    // Big destination
    doc
        .fillColor(COLORS.white)
        .fontSize(30)
        .font("Helvetica-Bold")
        .text(trip.location || "Travel Plan", MARGIN.left, 60, {
            width: pageW - MARGIN.left - MARGIN.right,
        });

    // Subtitle chips row (days · budget · travel with)
    const chips = [
        `📅 ${trip.days} Day${trip.days !== 1 ? "s" : ""}`,
        `💰 ${trip.budget || "N/A"}${trip.budgetAmount ? ` (${inr(trip.budgetAmount)})` : ""}`,
        `👥 ${trip.travelWith || "N/A"}`,
    ];

    doc
        .fillColor("rgba(255,255,255,0.7)")
        .fontSize(FONTS.body)
        .font("Helvetica")
        .text(chips.join("   ·   "), MARGIN.left, 138);

    // Date stamp
    doc
        .fillColor("rgba(255,255,255,0.5)")
        .fontSize(FONTS.small)
        .text(`Generated: ${new Date().toLocaleDateString("en-IN", { dateStyle: "long" })}`, MARGIN.left, 160);

    // Move below strip
    doc.y = 220;

    /* ══════════ SEASONAL INTELLIGENCE ══════════ */
    const sc = trip.seasonalContext;
    if (sc && sc.warningLevel) {
        const isIdeal = sc.warningLevel === "ideal";
        const isAvoid = sc.warningLevel === "avoid";

        const bgColor = isIdeal ? "#ecfdf5" : isAvoid ? "#fef2f2" : "#fffbeb";
        const strokeColor = isIdeal ? COLORS.success : isAvoid ? COLORS.danger : COLORS.accent;
        const icon = sc.season === "Summer" ? "☀" : sc.season === "Winter" ? "❄" : sc.season === "Monsoon" ? "🌧" : "🍂";

        const boxY = doc.y;
        doc
            .rect(MARGIN.left, boxY, pageW - MARGIN.left - MARGIN.right, sc.floodRisk ? 68 : 52)
            .fillAndStroke(bgColor, strokeColor);

        doc
            .fillColor(strokeColor)
            .fontSize(16)
            .font("Helvetica-Bold")
            .text(`${icon} ${sc.season} Travel: ${sc.warningLevel.toUpperCase()}`, MARGIN.left + 12, boxY + 10)

        doc
            .fillColor(COLORS.darkGray)
            .fontSize(FONTS.small)
            .font("Helvetica")
            .text(sc.warningMessage, MARGIN.left + 12, boxY + 30, {
                width: pageW - MARGIN.left - MARGIN.right - 24,
                lineGap: 2
            });

        if (sc.floodRisk && sc.season === "Monsoon") {
            doc
                .fillColor(COLORS.danger)
                .fontSize(FONTS.small)
                .font("Helvetica-Bold")
                .text("⚠ HIGH FLOOD RISK REGION DURING MONSOON", MARGIN.left + 12, boxY + 50);
        }

        doc.y = boxY + (sc.floodRisk ? 68 : 52) + 20;
    }

    // Executive summary block
    doc
        .fillColor(COLORS.bodyText)
        .fontSize(FONTS.h3)
        .font("Helvetica-Bold")
        .text("Executive Summary", MARGIN.left, doc.y);
    doc.moveDown(0.4);
    drawHR(doc);

    const summaryText = [
        `This travel itinerary for ${trip.location} was generated by an AI-based trip planning system,`,
        `powered by Google Gemini (${trip.days}-day plan for ${trip.travelWith || "travelers"}).`,
        "",
        `The itinerary incorporates real-time weather data, geographic route optimization using the`,
        `Haversine formula and greedy nearest-neighbor clustering, and dynamic business matching`,
        `from a verified partner network.`,
    ];

    if (trip.budgetBreakdown?.totalBudget > 0) {
        summaryText.push(
            "",
            `Budget allocation was performed using a constraint-aware optimization engine employing`,
            `both a Greedy Utility-Scored algorithm and a 0/1 Knapsack Dynamic Programming model.`,
            `The final itinerary was selected using the Knapsack model to maximize satisfaction score`,
            `(${Math.round((trip.budgetBreakdown.satisfactionScore || 0) * 100)}%) within a total budget of ${inr(trip.budgetBreakdown.totalBudget)}.`
        );
    }

    doc
        .fillColor(COLORS.darkGray)
        .fontSize(FONTS.body)
        .font("Helvetica")
        .text(summaryText.join("\n"), MARGIN.left, doc.y, {
            width: pageW - MARGIN.left - MARGIN.right,
            lineGap: 3,
        });

    doc.moveDown(1.5);

    // Quick stats grid (4 boxes)
    if (trip.itinerary?.length > 0) {
        const totalActivities = trip.itinerary.reduce((s, d) =>
            s + d.morning.length + d.afternoon.length + d.evening.length, 0
        );
        const freeActivities = trip.itinerary.reduce((s, d) =>
            [...d.morning, ...d.afternoon, ...d.evening].reduce(
                (a2, act) => a2 + (act.estimatedCost === 0 ? 1 : 0), s
            ), 0
        );

        const stats = [
            { label: "Total Activities", value: totalActivities },
            { label: "Free Activities", value: freeActivities },
            { label: "Trip Duration", value: `${trip.days} days` },
            { label: "Accommodation", value: trip.businessDetails?.hotel?.name || "TBD" },
        ];

        const boxW = (pageW - MARGIN.left - MARGIN.right - 30) / 4;
        const boxH = 52;
        let bx = MARGIN.left;
        const by = doc.y;

        stats.forEach(stat => {
            doc
                .rect(bx, by, boxW, boxH)
                .fillAndStroke(COLORS.lightGray, COLORS.lightGray);

            doc
                .fillColor(COLORS.primary)
                .fontSize(18)
                .font("Helvetica-Bold")
                .text(String(stat.value), bx + 8, by + 8, { width: boxW - 16, align: "center" });

            doc
                .fillColor(COLORS.midGray)
                .fontSize(FONTS.caption)
                .font("Helvetica")
                .text(stat.label, bx + 4, by + 34, { width: boxW - 8, align: "center" });

            bx += boxW + 10;
        });

        doc.y = by + boxH + 16;
    }

    addFooter(doc, 1);
}

/* ============================================================
   SECTION 2 — DAILY ITINERARY
   ============================================================ */
function drawItinerary(doc, trip, startPage) {
    let pageNum = startPage;

    trip.itinerary.forEach((day, dayIdx) => {
        // Day header
        doc.addPage();
        pageNum++;

        drawSectionBar(doc, `Day ${day.day} — Itinerary`, COLORS.primary);

        const periods = ["morning", "afternoon", "evening"];

        periods.forEach(period => {
            const activities = day[period] || [];
            if (activities.length === 0) return;

            // Period sub-header
            doc
                .fillColor(COLORS.primary)
                .fontSize(FONTS.h3)
                .font("Helvetica-Bold")
                .text(periodLabel(period), MARGIN.left, doc.y);
            doc.moveDown(0.3);

            activities.forEach((act, idx) => {
                // Check if we need a new page
                if (doc.y > doc.page.height - 160) {
                    addFooter(doc, pageNum);
                    doc.addPage();
                    pageNum++;
                }

                const name = act.activity || "Activity";
                const cost = act.estimatedCost > 0 ? inr(act.estimatedCost) : "Free";
                const tier = act.costTier ? ` [${act.costTier}]` : "";

                // Activity name row
                doc
                    .fillColor(COLORS.bodyText)
                    .fontSize(FONTS.body)
                    .font("Helvetica-Bold")
                    .text(`${idx + 1}. ${name}`, MARGIN.left + 12, doc.y, {
                        width: doc.page.width - MARGIN.left - MARGIN.right - 100,
                        continued: true,
                    })
                    .fillColor(act.estimatedCost === 0 ? COLORS.success : COLORS.accent)
                    .text(`${cost}${tier}`, {
                        align: "right",
                        width: 80,
                    });

                doc.moveDown(0.15);

                // Time + Duration chip
                if (act.startTime || act.duration) {
                    doc
                        .fillColor(COLORS.midGray)
                        .fontSize(FONTS.small)
                        .font("Helvetica")
                        .text(
                            `⏰ ${act.startTime || "--"}   ⏱ ${act.duration || "--"}${act.travelFromPrevious ? `   🚶 ${act.travelFromPrevious}` : ""}`,
                            MARGIN.left + 12,
                            doc.y
                        );
                    doc.moveDown(0.2);
                }

                // Description
                if (act.description && act.description !== "Loading details...") {
                    doc
                        .fillColor(COLORS.darkGray)
                        .fontSize(FONTS.small)
                        .font("Helvetica")
                        .text(clamp(act.description, 180), MARGIN.left + 12, doc.y, {
                            width: doc.page.width - MARGIN.left - MARGIN.right - 24,
                            lineGap: 2,
                        });
                    doc.moveDown(0.2);
                }

                // Address
                if (act.address && act.address !== trip.location) {
                    doc
                        .fillColor(COLORS.midGray)
                        .fontSize(FONTS.caption)
                        .text(`📍 ${clamp(act.address, 100)}`, MARGIN.left + 12, doc.y);
                    doc.moveDown(0.15);
                }

                // Google Maps link
                if (act.placeUrl) {
                    doc
                        .fillColor(COLORS.secondary)
                        .fontSize(FONTS.caption)
                        .text("🔗 View on Maps / Web", MARGIN.left + 12, doc.y, {
                            link: act.placeUrl,
                            underline: true,
                        });
                    doc.moveDown(0.3);
                }

                doc.moveDown(0.3);
            });

            doc.moveDown(0.4);
            drawHR(doc, COLORS.lightGray, 0.5);
        });

        addFooter(doc, pageNum);
    });

    return pageNum;
}

/* ============================================================
   SECTION 3 — SMART BUDGET BREAKDOWN
   ============================================================ */
function drawBudgetSection(doc, trip, pageNum) {
    const bd = trip.budgetBreakdown;
    if (!bd || !bd.totalBudget) return pageNum;

    doc.addPage();
    pageNum++;

    drawSectionBar(doc, "💰 Smart Budget Breakdown", COLORS.dark);

    const pageW = doc.page.width;
    const usableW = pageW - MARGIN.left - MARGIN.right;

    // Summary row
    doc
        .fillColor(COLORS.primary)
        .fontSize(22)
        .font("Helvetica-Bold")
        .text(inr(bd.totalBudget), MARGIN.left, doc.y, { continued: true })
        .fillColor(COLORS.midGray)
        .fontSize(FONTS.h2)
        .font("Helvetica")
        .text("  Total Budget", { baseline: "bottom" });

    doc.moveDown(0.5);

    // Algorithm badge
    const algo = bd.algorithm === "knapsack"
        ? "🧠 Knapsack DP — Research-Grade Optimization"
        : "⚡ Greedy — Baseline Allocation";
    doc
        .fillColor(bd.algorithm === "knapsack" ? COLORS.primary : COLORS.accent)
        .fontSize(FONTS.body)
        .font("Helvetica-Bold")
        .text(algo, MARGIN.left, doc.y);

    doc.moveDown(0.4);

    // Satisfaction score
    const scoreStr = `${Math.round((bd.satisfactionScore || 0) * 100)}%`;
    const utilStr = `${Math.round((bd.budgetUtilization || 0) * 100)}%`;

    doc
        .fillColor(COLORS.darkGray)
        .fontSize(FONTS.body)
        .font("Helvetica-Bold")
        .text(`Satisfaction Score: `, MARGIN.left, doc.y, { continued: true })
        .fillColor(COLORS.success)
        .text(scoreStr, { continued: true })
        .fillColor(COLORS.darkGray)
        .text(`    Budget Utilization: `, { continued: true })
        .fillColor(COLORS.primary)
        .text(utilStr);

    doc.moveDown(0.8);
    drawHR(doc);

    // Allocation bars
    const alloc = bd.allocated || {};
    const total = bd.totalBudget;

    const segments = [
        { label: "🏨 Stay", value: alloc.stay, color: COLORS.primary },
        { label: "🍽️  Food", value: alloc.food, color: COLORS.accent },
        { label: "🚗 Transport", value: alloc.transport, color: COLORS.success },
        { label: "🎯 Activities", value: alloc.activities, color: COLORS.danger },
    ];

    // Two columns
    const colW = (usableW - 30) / 2;
    let col = 0;
    const startY = doc.y;
    let maxY = startY;

    segments.forEach((seg, i) => {
        const x = MARGIN.left + (col === 0 ? 0 : colW + 30);
        const y = i < 2 ? startY : maxY + 22;

        drawTextBar(doc, seg.label, seg.value, total, seg.color, x, y, colW - 60);

        col = col === 0 ? 1 : 0;
        if (i === 1) maxY = y + 28;
        if (i === 3) doc.y = y + 28;
    });

    doc.moveDown(1.2);

    // Spent vs Allocated table (if actualSpent is present)
    const spent = bd.actualSpent;
    if (spent && Object.values(spent).some(v => v > 0)) {
        drawHR(doc);
        doc
            .fillColor(COLORS.darkGray)
            .fontSize(FONTS.h3)
            .font("Helvetica-Bold")
            .text("Actual vs. Allocated", MARGIN.left, doc.y);
        doc.moveDown(0.4);

        const headers = ["Category", "Allocated", "Actual Spent", "Variance"];
        const rows = [
            ["Stay", inr(alloc.stay), inr(spent.stay), inr((spent.stay || 0) - (alloc.stay || 0))],
            ["Food", inr(alloc.food), inr(spent.food), inr((spent.food || 0) - (alloc.food || 0))],
            ["Transport", inr(alloc.transport), inr(spent.transport), inr((spent.transport || 0) - (alloc.transport || 0))],
            ["Activities", inr(alloc.activities), inr(spent.activities), inr((spent.activities || 0) - (alloc.activities || 0))],
        ];

        const colWidths = [120, 90, 100, 90];
        let tx = MARGIN.left;

        // Header row
        doc
            .rect(MARGIN.left, doc.y, usableW, 18)
            .fill(COLORS.primary);

        headers.forEach((h, i) => {
            doc
                .fillColor(COLORS.white)
                .fontSize(FONTS.small)
                .font("Helvetica-Bold")
                .text(h, tx + 4, doc.y - 14, { width: colWidths[i] - 8 });
            tx += colWidths[i];
        });
        doc.moveDown(0.6);

        // Data rows
        rows.forEach((row, rowIdx) => {
            tx = MARGIN.left;
            const rowY = doc.y;

            if (rowIdx % 2 === 0) {
                doc.rect(MARGIN.left, rowY, usableW, 16).fill("#f8f8fc");
            }

            row.forEach((cell, i) => {
                const isVariance = i === 3;
                const numVal = parseFloat(cell.replace(/[₹,]/g, ""));
                const color = isVariance
                    ? numVal > 0 ? COLORS.danger : COLORS.success
                    : COLORS.darkGray;

                doc
                    .fillColor(color)
                    .fontSize(FONTS.small)
                    .font(isVariance ? "Helvetica-Bold" : "Helvetica")
                    .text(cell, tx + 4, rowY + 3, { width: colWidths[i] - 8 });
                tx += colWidths[i];
            });

            doc.moveDown(0.6);
        });
    }

    addFooter(doc, pageNum);
    return pageNum;
}

/* ============================================================
   SECTION 4 — RESEARCH OPTIMIZATION INSIGHTS
   ============================================================ */
function drawResearchSection(doc, trip, pageNum) {
    const rm = trip.researchMetrics;
    if (!rm) return pageNum;

    doc.addPage();
    pageNum++;

    drawSectionBar(doc, "📊 Optimization Insights (Research Metrics)", COLORS.dark);

    const pageW = doc.page.width;

    // Intro
    doc
        .fillColor(COLORS.darkGray)
        .fontSize(FONTS.body)
        .font("Helvetica")
        .text(
            "The following metrics compare the two optimization algorithms applied during itinerary generation. " +
            "This data supports the experimental section of an academic publication on AI-assisted travel planning.",
            MARGIN.left, doc.y,
            { width: pageW - MARGIN.left - MARGIN.right, lineGap: 3 }
        );
    doc.moveDown(0.8);
    drawHR(doc);

    // Comparison table
    const metrics = [
        { metric: "Satisfaction Score", greedy: `${Math.round((rm.greedySatisfaction || 0) * 100)}%`, knapsack: `${Math.round((rm.knapsackSatisfaction || 0) * 100)}%` },
        { metric: "Budget Utilization", greedy: `${Math.round((rm.greedyUtilization || 0) * 100)}%`, knapsack: `${Math.round((rm.knapsackUtilization || 0) * 100)}%` },
        { metric: "Time Complexity", greedy: "O(n log n)", knapsack: "O(n × B/100)" },
        { metric: "Processing Time", greedy: "~1ms", knapsack: `~${rm.processingTimeMs || 0}ms total` },
        { metric: "Algorithm Class", greedy: "Heuristic", knapsack: "Dynamic Programming" },
    ];

    const usableW = pageW - MARGIN.left - MARGIN.right;
    const colWs = [180, 120, 120];
    const headers = ["Metric", "Greedy (Baseline)", "Knapsack (Optimized)"];

    // Header
    let tx = MARGIN.left;
    doc.rect(MARGIN.left, doc.y, usableW, 20).fill(COLORS.dark);
    headers.forEach((h, i) => {
        doc
            .fillColor(COLORS.white)
            .fontSize(FONTS.body)
            .font("Helvetica-Bold")
            .text(h, tx + 6, doc.y - 15, { width: colWs[i] - 12 });
        tx += colWs[i];
    });
    doc.moveDown(0.7);

    // Rows
    metrics.forEach((row, idx) => {
        tx = MARGIN.left;
        const rowY = doc.y;

        if (idx % 2 === 0) {
            doc.rect(MARGIN.left, rowY, usableW, 18).fill("#f1f0ff");
        }

        const cells = [row.metric, row.greedy, row.knapsack];
        cells.forEach((cell, i) => {
            const color = i === 2 ? COLORS.primary : COLORS.darkGray;
            doc
                .fillColor(color)
                .fontSize(FONTS.body)
                .font(i === 2 ? "Helvetica-Bold" : "Helvetica")
                .text(cell, tx + 6, rowY + 4, { width: colWs[i] - 12 });
            tx += colWs[i];
        });
        doc.moveDown(0.65);
    });

    doc.moveDown(0.8);

    // Improvement callout box
    const improvement = ((rm.knapsackSatisfaction || 0) - (rm.greedySatisfaction || 0)) * 100;
    if (improvement >= 0) {
        const boxY = doc.y;
        doc
            .rect(MARGIN.left, boxY, usableW, 52)
            .fillAndStroke("#eef2ff", COLORS.primary);

        doc
            .fillColor(COLORS.primary)
            .fontSize(26)
            .font("Helvetica-Bold")
            .text(`+${improvement.toFixed(1)}%`, MARGIN.left + 16, boxY + 9, {
                continued: true,
            })
            .fillColor(COLORS.darkGray)
            .fontSize(FONTS.body)
            .font("Helvetica")
            .text(
                `  satisfaction improvement from Greedy → Knapsack optimization.\n` +
                `  This is the core research contribution demonstrating the advantage of DP-based selection.`,
                {
                    lineGap: 3,
                }
            );

        doc.y = boxY + 62;
    }

    doc.moveDown(0.8);

    // Mathematical model
    drawHR(doc);
    doc
        .fillColor(COLORS.darkGray)
        .fontSize(FONTS.h3)
        .font("Helvetica-Bold")
        .text("Mathematical Model", MARGIN.left, doc.y);
    doc.moveDown(0.4);

    const formulas = [
        "Utility Function:   u_i = (w_priority × w_preference × popularity_i) / cost_i",
        "Satisfaction Score: S = Σ u(selected_i) / Σ u(all_i)  ∈ [0, 1]",
        "Knapsack Problem:   max Σ u_i·x_i  s.t.  Σ cost_i·x_i ≤ B_activities,  x_i ∈ {0,1}",
        "Budget Utilization: U = Σ actual_spent / total_budget",
    ];

    doc
        .rect(MARGIN.left, doc.y, usableW, formulas.length * 16 + 16)
        .fill("#1e1b4b");

    const fby = doc.y;
    formulas.forEach((f, i) => {
        doc
            .fillColor(i % 2 === 0 ? "#a5b4fc" : COLORS.white)
            .fontSize(FONTS.small)
            .font("Helvetica")
            .text(f, MARGIN.left + 12, fby + 8 + i * 16);
    });

    doc.y = fby + formulas.length * 16 + 24;

    addFooter(doc, pageNum);
    return pageNum;
}

/* ============================================================
   SECTION 5 — ACCOMMODATION & BUSINESS PARTNERS
   ============================================================ */
function drawAccommodationSection(doc, trip, pageNum) {
    const bd = trip.businessDetails;
    if (!bd || (!bd.hotel && !bd.rental && !bd.toursPerDay)) return pageNum;

    // Check if we need a new page or if there's room
    if (doc.y > doc.page.height - 220) {
        addFooter(doc, pageNum);
        doc.addPage();
        pageNum++;
    }

    drawSectionBar(doc, "🏨 Accommodation & Partners", COLORS.secondary);

    const pageW = doc.page.width;
    const usableW = pageW - MARGIN.left - MARGIN.right;

    // Hotel
    if (bd.hotel?.name) {
        doc
            .fillColor(COLORS.darkGray)
            .fontSize(FONTS.h3)
            .font("Helvetica-Bold")
            .text("Selected Hotel", MARGIN.left, doc.y);
        doc.moveDown(0.3);

        const hotelRows = [
            ["Hotel Name", bd.hotel.name],
            ["Address", bd.hotel.address || "N/A"],
            ["Star Rating", bd.hotel.starRating ? `${"⭐".repeat(bd.hotel.starRating)}` : "N/A"],
            ["Price Per Night", bd.hotel.selectedRoom?.pricePerNight ? inr(bd.hotel.selectedRoom.pricePerNight) : "N/A"],
            ["Room Type", bd.hotel.selectedRoom?.type || "N/A"],
            ["Contact Phone", bd.hotel.contact?.phone || "N/A"],
            ["Website", bd.hotel.contact?.website || "N/A"],
        ];

        hotelRows.forEach(([key, val]) => {
            if (val === "N/A" || !val) return;
            doc
                .fillColor(COLORS.midGray)
                .fontSize(FONTS.body)
                .font("Helvetica-Bold")
                .text(`${key}: `, MARGIN.left + 8, doc.y, { continued: true, width: 120 })
                .fillColor(COLORS.bodyText)
                .font("Helvetica")
                .text(val);
            doc.moveDown(0.25);
        });

        doc.moveDown(0.5);
    }

    // Rental
    if (bd.rental?.name) {
        drawHR(doc, COLORS.lightGray, 0.5);
        doc
            .fillColor(COLORS.darkGray)
            .fontSize(FONTS.h3)
            .font("Helvetica-Bold")
            .text("Vehicle Rental", MARGIN.left, doc.y);
        doc.moveDown(0.3);

        [
            ["Provider", bd.rental.name],
            ["Vehicle", `${bd.rental.vehicleType || ""} ${bd.rental.model || ""}`.trim()],
            ["Price/Day", inr(bd.rental.pricePerDay)],
            ["Contact", bd.rental.contact],
        ].forEach(([key, val]) => {
            if (!val) return;
            doc
                .fillColor(COLORS.midGray).fontSize(FONTS.body).font("Helvetica-Bold")
                .text(`${key}: `, MARGIN.left + 8, doc.y, { continued: true, width: 100 })
                .fillColor(COLORS.bodyText).font("Helvetica")
                .text(val);
            doc.moveDown(0.25);
        });

        doc.moveDown(0.5);
    }

    addFooter(doc, pageNum);
    return pageNum;
}

/* ============================================================
   MAIN EXPORT — Generate PDF and pipe to response
   ============================================================ */

/**
 * Generate a complete trip PDF and stream it to the HTTP response.
 * @param {Object} trip - Mongoose Trip document (or lean object)
 * @param {Object} res  - Express response object
 */
export async function generateTripPDF(trip, res) {
    const doc = new PDFDocument({
        size: "A4",
        margins: { top: MARGIN.top, left: MARGIN.left, right: MARGIN.right, bottom: MARGIN.bottom },
        info: {
            Title: `Travel Plan — ${trip.location}`,
            Author: "Around the World — AI Travel Companion",
            Subject: "AI-Generated Travel Itinerary with Budget Optimization",
            Keywords: "travel, itinerary, AI, budget optimizer, knapsack",
        },
    });

    // Pipe to response
    doc.pipe(res);

    // ── Page 1: Cover  ─────────────────────────────────────────
    drawCoverPage(doc, trip);
    let pageNum = 1;

    // ── Pages 2…N: Daily Itinerary ─────────────────────────────
    if (trip.itinerary?.length > 0) {
        pageNum = drawItinerary(doc, trip, pageNum);
    }

    // ── Budget Breakdown ───────────────────────────────────────
    if (trip.budgetBreakdown?.totalBudget > 0) {
        pageNum = drawBudgetSection(doc, trip, pageNum);
    }

    // ── Research Insights ──────────────────────────────────────
    if (trip.researchMetrics?.greedySatisfaction) {
        pageNum = drawResearchSection(doc, trip, pageNum);
    }

    // ── Accommodation ──────────────────────────────────────────
    if (trip.businessDetails) {
        pageNum = drawAccommodationSection(doc, trip, pageNum);
    }

    doc.end();
}
